version: '3'
services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'something'
      MYSQL_ROOT_PASSWORD: 'something'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
     - static-network

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=vehicle_service -user=root -password=something -connectRetries=60 migrate
    volumes:
        - .:/flyway/sql
    depends_on:
        - db
    networks:
     - static-network

  flyway2:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=user_service -user=root -password=something -connectRetries=60 migrate
    volumes:
        - .:/flyway/user_service
    depends_on:
        - db
    networks:
     - static-network

  flyway3:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=test3 -user=root -password=something -connectRetries=60 migrate
    volumes:
        - .:/flyway/sql3
    depends_on:
        - db
    networks:
     - static-network


volumes:
  my-db:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
