version: '3'
services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'something'
      MYSQL_ROOT_PASSWORD: 'something'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=vehicle_service -user=root -password=something -connectRetries=60 migrate
    volumes:
        - .:/flyway/sql
    depends_on:
        - db

  flyway2:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=test2 -user=root -password=something -connectRetries=60 migrate
    volumes:
        - .:/flyway/sql2
    depends_on:
        - db

  flyway3:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=test3 -user=root -password=something -connectRetries=60 migrate
    volumes:
        - .:/flyway/sql3
    depends_on:
        - db


volumes:
  my-db: