//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalAPI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.soapservice.ftnxml.com/model/", ConfigurationName="CarRentalAPI.CarRentalApiClient")]
    public interface CarRentalApiClient
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CarRentalAPI.BrandByIdResponse1> BrandByIdAsync(CarRentalAPI.BrandByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CarRentalAPI.AllBrandsResponse> AllBrandsAsync(CarRentalAPI.AllBrandsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CarRentalAPI.AddBrandResponse1> AddBrandAsync(CarRentalAPI.AddBrandRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CarRentalAPI.RegisterAgentResponse1> RegisterAgentAsync(CarRentalAPI.RegisterAgentRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.soapservice.ftnxml.com/model/")]
    public partial class BrandByIdRequest
    {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.soapservice.ftnxml.com/model/")]
    public partial class Model
    {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.soapservice.ftnxml.com/model/")]
    public partial class Brand
    {
        
        private long idField;
        
        private string nameField;
        
        private Model[] modelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Model", Order=2)]
        public Model[] Model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.soapservice.ftnxml.com/model/")]
    public partial class BrandByIdResponse
    {
        
        private Brand brandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Brand Brand
        {
            get
            {
                return this.brandField;
            }
            set
            {
                this.brandField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BrandByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.soapservice.ftnxml.com/model/", Order=0)]
        public CarRentalAPI.BrandByIdRequest BrandByIdRequest;
        
        public BrandByIdRequest1()
        {
        }
        
        public BrandByIdRequest1(CarRentalAPI.BrandByIdRequest BrandByIdRequest)
        {
            this.BrandByIdRequest = BrandByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BrandByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.soapservice.ftnxml.com/model/", Order=0)]
        public CarRentalAPI.BrandByIdResponse BrandByIdResponse;
        
        public BrandByIdResponse1()
        {
        }
        
        public BrandByIdResponse1(CarRentalAPI.BrandByIdResponse BrandByIdResponse)
        {
            this.BrandByIdResponse = BrandByIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.soapservice.ftnxml.com/model/")]
    public partial class AllBrandsRequest
    {
        
        private string testField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string test
        {
            get
            {
                return this.testField;
            }
            set
            {
                this.testField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllBrandsRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.soapservice.ftnxml.com/model/", Order=0)]
        public CarRentalAPI.AllBrandsRequest AllBrandsRequest;
        
        public AllBrandsRequest1()
        {
        }
        
        public AllBrandsRequest1(CarRentalAPI.AllBrandsRequest AllBrandsRequest)
        {
            this.AllBrandsRequest = AllBrandsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllBrandsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllBrandsResponse", Namespace="www.soapservice.ftnxml.com/model/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Brands", IsNullable=false)]
        public CarRentalAPI.Brand[] AllBrandsResponse1;
        
        public AllBrandsResponse()
        {
        }
        
        public AllBrandsResponse(CarRentalAPI.Brand[] AllBrandsResponse1)
        {
            this.AllBrandsResponse1 = AllBrandsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.soapservice.ftnxml.com/model/")]
    public partial class AddBrandRequest
    {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.soapservice.ftnxml.com/model/")]
    public partial class AddBrandResponse
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBrandRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.soapservice.ftnxml.com/model/", Order=0)]
        public CarRentalAPI.AddBrandRequest AddBrandRequest;
        
        public AddBrandRequest1()
        {
        }
        
        public AddBrandRequest1(CarRentalAPI.AddBrandRequest AddBrandRequest)
        {
            this.AddBrandRequest = AddBrandRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBrandResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.soapservice.ftnxml.com/model/", Order=0)]
        public CarRentalAPI.AddBrandResponse AddBrandResponse;
        
        public AddBrandResponse1()
        {
        }
        
        public AddBrandResponse1(CarRentalAPI.AddBrandResponse AddBrandResponse)
        {
            this.AddBrandResponse = AddBrandResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.soapservice.ftnxml.com/model/")]
    public partial class RegisterAgentRequest
    {
        
        private string usernameField;
        
        private string emailField;
        
        private string passwordField;
        
        private string confirmPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string confirmPassword
        {
            get
            {
                return this.confirmPasswordField;
            }
            set
            {
                this.confirmPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.soapservice.ftnxml.com/model/")]
    public partial class RegisterAgentResponse
    {
        
        private long idField;
        
        private long statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterAgentRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.soapservice.ftnxml.com/model/", Order=0)]
        public CarRentalAPI.RegisterAgentRequest RegisterAgentRequest;
        
        public RegisterAgentRequest1()
        {
        }
        
        public RegisterAgentRequest1(CarRentalAPI.RegisterAgentRequest RegisterAgentRequest)
        {
            this.RegisterAgentRequest = RegisterAgentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterAgentResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.soapservice.ftnxml.com/model/", Order=0)]
        public CarRentalAPI.RegisterAgentResponse RegisterAgentResponse;
        
        public RegisterAgentResponse1()
        {
        }
        
        public RegisterAgentResponse1(CarRentalAPI.RegisterAgentResponse RegisterAgentResponse)
        {
            this.RegisterAgentResponse = RegisterAgentResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface CarRentalApiClientChannel : CarRentalAPI.CarRentalApiClient, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CarRentalApiClientClient : System.ServiceModel.ClientBase<CarRentalAPI.CarRentalApiClient>, CarRentalAPI.CarRentalApiClient
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CarRentalApiClientClient() : 
                base(CarRentalApiClientClient.GetDefaultBinding(), CarRentalApiClientClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CarRentalApiClientSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRentalApiClientClient(EndpointConfiguration endpointConfiguration) : 
                base(CarRentalApiClientClient.GetBindingForEndpoint(endpointConfiguration), CarRentalApiClientClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRentalApiClientClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CarRentalApiClientClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRentalApiClientClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CarRentalApiClientClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRentalApiClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalAPI.BrandByIdResponse1> CarRentalAPI.CarRentalApiClient.BrandByIdAsync(CarRentalAPI.BrandByIdRequest1 request)
        {
            return base.Channel.BrandByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalAPI.BrandByIdResponse1> BrandByIdAsync(CarRentalAPI.BrandByIdRequest BrandByIdRequest)
        {
            CarRentalAPI.BrandByIdRequest1 inValue = new CarRentalAPI.BrandByIdRequest1();
            inValue.BrandByIdRequest = BrandByIdRequest;
            return ((CarRentalAPI.CarRentalApiClient)(this)).BrandByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalAPI.AllBrandsResponse> CarRentalAPI.CarRentalApiClient.AllBrandsAsync(CarRentalAPI.AllBrandsRequest1 request)
        {
            return base.Channel.AllBrandsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalAPI.AllBrandsResponse> AllBrandsAsync(CarRentalAPI.AllBrandsRequest AllBrandsRequest)
        {
            CarRentalAPI.AllBrandsRequest1 inValue = new CarRentalAPI.AllBrandsRequest1();
            inValue.AllBrandsRequest = AllBrandsRequest;
            return ((CarRentalAPI.CarRentalApiClient)(this)).AllBrandsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalAPI.AddBrandResponse1> CarRentalAPI.CarRentalApiClient.AddBrandAsync(CarRentalAPI.AddBrandRequest1 request)
        {
            return base.Channel.AddBrandAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalAPI.AddBrandResponse1> AddBrandAsync(CarRentalAPI.AddBrandRequest AddBrandRequest)
        {
            CarRentalAPI.AddBrandRequest1 inValue = new CarRentalAPI.AddBrandRequest1();
            inValue.AddBrandRequest = AddBrandRequest;
            return ((CarRentalAPI.CarRentalApiClient)(this)).AddBrandAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalAPI.RegisterAgentResponse1> CarRentalAPI.CarRentalApiClient.RegisterAgentAsync(CarRentalAPI.RegisterAgentRequest1 request)
        {
            return base.Channel.RegisterAgentAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalAPI.RegisterAgentResponse1> RegisterAgentAsync(CarRentalAPI.RegisterAgentRequest RegisterAgentRequest)
        {
            CarRentalAPI.RegisterAgentRequest1 inValue = new CarRentalAPI.RegisterAgentRequest1();
            inValue.RegisterAgentRequest = RegisterAgentRequest;
            return ((CarRentalAPI.CarRentalApiClient)(this)).RegisterAgentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CarRentalApiClientSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CarRentalApiClientSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/soap/service");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CarRentalApiClientClient.GetBindingForEndpoint(EndpointConfiguration.CarRentalApiClientSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CarRentalApiClientClient.GetEndpointAddress(EndpointConfiguration.CarRentalApiClientSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            CarRentalApiClientSoap11,
        }
    }
}
