server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-experience
          uri: lb://customer-experience
          predicates:
            - Path=/customer-experience/**
          filters:
            - RewritePath=/customer-experience/(?<path>.*), /$\{path}
        - id: order-processing
          uri: lb://order-processing
          predicates:
            - Path=/order-processing/**
          filters:
            - RewritePath=/order-processing/(?<path>.*), /$\{path}
        - id: soap-service
          uri: lb://soap-service
          predicates:
            - Path=/soap-service/**
          filters:
            - RewritePath=/soap-service/(?<path>.*), /$\{path}
        - id: user-managament
          uri: lb://user-managament
          predicates:
            - Path=/user-managament/**
          filters:
            - RewritePath=/user-managament/(?<path>.*), /$\{path}
        - id: vehicle-managament
          uri: lb://vehicle-managament
          predicates:
            - Path=/vehicle-managament/**
          filters:
            - RewritePath=/vehicle-managament/(?<path>.*), /$\{path}