dos2unix.exe ..\backend\eureka-server\Dockerfile
dos2unix.exe ..\backend\eureka-server\entrypoint.sh
dos2unix.exe ..\backend\services\customer-experience\Dockerfile
dos2unix.exe ..\backend\services\customer-experience\entrypoint.sh
dos2unix.exe ..\backend\services\eureka-zuul\Dockerfile
dos2unix.exe ..\backend\services\eureka-zuul\entrypoint.sh
dos2unix.exe ..\backend\services\order-processing\Dockerfile
dos2unix.exe ..\backend\services\order-processing\entrypoint.sh
dos2unix.exe ..\backend\services\soap-service\Dockerfile
dos2unix.exe ..\backend\services\soap-service\entrypoint.sh
dos2unix.exe ..\backend\services\user-management\Dockerfile
dos2unix.exe ..\backend\services\user-management\entrypoint.sh
dos2unix.exe ..\backend\services\vehicle-management\Dockerfile
dos2unix.exe ..\backend\services\vehicle-management\entrypoint.sh